---
- hosts: Mikrotik
  connection: network_cli
  gather_facts: no

  tasks:
  - name: Grupo MK
    routeros_command:
       commands:
         - /ip firewall filter add chain=forward action=accept
         - /ip firewall filter add action=accept chain=input protocol=icmp comm>
         - /ip firewall filter add action=accept chain=output protocol=icmp com>

- hosts: IPtables
  become: true
  become_user: root
  vars:
      host_name: localhost
 
 
  tasks:
          # ------- filter rules -------

  - name: change default chain policy (used to clean rules)
    ansible.builtin.iptables:
      chain: INPUT
      policy: ACCEPT

  - name: Block specific IP
    ansible.builtin.iptables:
      chain: INPUT
      source: 8.8.8.8
      jump: DROP
    become: yes


  - name: Accept INPUT
    ansible.builtin.iptables:
      chain: INPUT
      source: 192.168.1.1
      jump: ACCEPT
    become: yes

  - name: Accept OUTPUT
    ansible.builtin.iptables:
      chain: OUTPUT
      destination: 192.168.1.1
      jump: ACCEPT
    become: yes

  - name: Allow new incoming SYN packets on TCP port 22 (SSH)
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: Accept new SSH connections.




  - name: Drop INPUT
    ansible.builtin.iptables:
      chain: INPUT
      policy: DROP
    become: yes

  - name: Accept INPUT
    ansible.builtin.iptables:
      chain: OUTPUT
      policy: DROP
    become: yes